version: '3.7'

services:
  elasticsearch:
    restart: always
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    restart: always
    image: kibana:7.14.0
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"   
    depends_on:
      - elasticsearch

